name: Lint and unit test code

on: push

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v1
          with: 
              python-version: 3.11
        - name: Install Dependencies
          run: |
              make install
        - name: Code linting
          run: |
              make lint
        - name: Unit testing using pytest
          run: |
              make test