name: Deploy to Azure

on: push

jobs:
  lint-and-test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v1
          with: 
              python-version: 3.11
        - name: Install Dependencies
          run: |
              make setup
              make install
        - name: Code linting
          run: |
              make lint
        - name: Unit testing using pytest
          run: |
              make test
  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Azure Pipeline to deploy the app"
        uses: Azure/pipelines@releases/v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/binhtruongvu97/udacity-devops'
          azure-pipeline-name: 'remichan97.udacity-devops-cicd'
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'